name: Python CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "xinference"
          args: "--config setup.cfg"
      - name: black
        uses: psf/black@stable
        with:
          src: "xinference"
          options: "--check"
      - uses: isort/isort-action@master
        with:
          sortPaths: "xinference"
          configuration: "--check-only --diff --sp setup.cfg"
      - name: mypy
        run: pip install mypy && mypy --install-types --non-interactive xinference
      - name: codespell
        run: pip install codespell && codespell xinference

  build_test_job:
    runs-on: ${{ matrix.os }}
    needs: lint
    env:
      CONDA_ENV: test
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        module: [ "xinference" ]
        exclude:
          - { os: macos-latest, python-version: 3.9 }
          - { os: macos-latest, python-version: 3.10 }
          - { os: windows-latest, python-version: 3.9 }
          - { os: windows-latest, python-version: 3.10 }
        include:
          - { os: self-hosted, module: gpu, python-version: 3.9}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up conda ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        if: ${{ matrix.module != 'gpu' }}
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: ${{ env.CONDA_ENV }}
        run: |
          export PYTHON=/root/miniconda3/bin/pytho

      - name: Set up conda GPU ${{ matrix.python-version }}
        if: ${{ matrix.module == 'gpu' }}
        run: |
          export PYTHON=/root/miniconda3/envs/inference_test/bin/python

      - name: Install dependencies
        env:
          MODULE: ${{ matrix.module }}
        run: |
          ${{ env.PYTHON }} -m pip install llama-cpp-python>=0.2.0
          ${{ env.PYTHON }} -m pip install transformers
          ${{ env.PYTHON }} -m pip install torch
          ${{ env.PYTHON }} -m pip install accelerate
          ${{ env.PYTHON }} -m pip install sentencepiece
          ${{ env.PYTHON }} -m pip install transformers_stream_generator
          ${{ env.PYTHON }} -m pip install bitsandbytes
          ${{ env.PYTHON }} -m pip install ctransformers
          ${{ env.PYTHON }} -m pip install sentence-transformers
          ${{ env.PYTHON }} -m pip install s3fs
          ${{ env.PYTHON }} -m pip install modelscope
          ${{ env.PYTHON }} -m pip install diffusers
          ${{ env.PYTHON }} -m pip install -e ".[dev]"
        working-directory: .

      - name: Test with pytest
        env:
          MODULE: ${{ matrix.module }}
        run: |
          if [ "$MODULE" == "gpu" ]; then
            ${{ env.PYTHON }} -m pytest --timeout=1500 \
              -W ignore::PendingDeprecationWarning \
              --cov-config=setup.cfg --cov-report=xml --cov=xinference xinference/model/multimodal/tests/test_stable_diffusion.py
          else
            ${{ env.PYTHON }} -m pytest --timeout=1500 \
              -W ignore::PendingDeprecationWarning \
              --cov-config=setup.cfg --cov-report=xml --cov=xinference xinference/tests/test_client.py
            ${{ env.PYTHON }} -m pytest --timeout=1500 \
              -W ignore::PendingDeprecationWarning \
              --cov-config=setup.cfg --cov-report=xml --cov=xinference --ignore xinference/tests/test_client.py --ignore xinference/model/multimodal/tests/test_stable_diffusion.py xinference
          fi
        working-directory: .
